# Generated by Django 2.2.3 on 2019-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20190721_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='desctiption',
            field=models.TextField(null=True),
        ),
    ]
