# Generated by Django 2.2.3 on 2019-07-28 15:07

from django.db import migrations

def clear_null_title(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    for pokemon in Pokemon.objects.all():
        if pokemon.title_en == None:
            pokemon.title_en = ''
        if pokemon.title_jp == None:
            pokemon.title_en = ''

class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20190726_1251'),
    ]

    operations = [
        migrations.RunPython(clear_null_title),
    ]
